#!/usr/bin/env bash

mode=$1
year=$2
day=$3

flags="-DYEAR=\"$year\" -DDAY=\"$day\""

[[ -d "hs-out" ]] || mkdir -p "hs-out"

command cat >src/extra/Opts.hs <<OPTS
module Opts where

input_file_path :: FilePath
input_file_path = "../inputs/${year}-${day}.txt"

test_input_file_path :: FilePath
test_input_file_path = "../test_inputs/${year}-${day}.txt"

test_output_file_path :: FilePath
test_output_file_path = "../test_outputs/${year}-${day}.txt"
OPTS

case $mode in
test)
	ghci -DTEST_MODE -isrc/extra src/main.hs src/sol/${year}-${day}.hs <<CMD
main
:q
CMD
	;;
run)
	ghc -dynamic -O2 -isrc/extra src/main.hs src/sol/${year}-${day}.hs -o ./hs-out/${year}-${day} &&
		./hs-out/${year}-${day} | tee ../outputs/$year-$day.txt
	;;
*)
	>&2 echo unreachable
	exit 1
	;;
esac
