#!/usr/bin/env bash

mode=$1
year=$2
day=$3

command cat >src/extra/opts.rs <<OPTS
#![allow(dead_code)]
pub const INPUT_FILE_PATH: &str = "../inputs/${year}-${day}.txt";
pub const TEST_INPUT_FILE_PATH: &str = "../test_inputs/${year}-${day}.txt";
pub const TEST_OUTPUT_FILE_PATH: &str = "../test_outputs/${year}-${day}.txt";

#[path = "../sol/${year}-${day}.rs"]
pub mod sol;
OPTS

mkdir -p build

case $mode in
test)
	rustc -O --test -o build/${year}-${day}-test src/main.rs &&
		./build/${year}-${day}-test
	;;
run)
	rustc -O -o build/${year}-${day}-test src/main.rs &&
		./build/${year}-${day}-test | tee ../outputs/$year-$day.txt
	;;
*)
	>&2 echo unreachable
	exit 1
	;;
esac
